# Generated by Django 5.2.17 on 2026-09-02 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('seller_reviewer', 'Seller reviewer'), ('security_admin', 'Security admin')], max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('assigned_by_id', models.UUIDField(null=True)),
                ('assigned_reason', models.TextField()),
                ('active_from', models.DateTimeField()),
                ('revoked_by_id', models.UUIDField(null=True)),
                ('revoked_reason', models.TextField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'access_role_assignment',
                'indexes': [models.Index(fields=['account_id', 'state', 'role'], name='access_role_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('account_id', 'role'), name='access_one_active_role_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by_id__isnull', True), ('revoked_reason__isnull', True), ('state', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by_id__isnull', False), ('revoked_reason__isnull', False), ('state', 'revoked')), _connector='OR'), name='access_role_assignment_revocation_state'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('active_from')), _connector='OR'), name='access_role_assignment_revoked_after_start'), models.CheckConstraint(condition=models.Q(('role__in', ('seller_reviewer', 'security_admin'))), name='access_role_assignment_known_role'), models.CheckConstraint(condition=models.Q(('assigned_reason', ''), _negated=True), name='access_role_assignment_reason_present'), models.CheckConstraint(condition=models.Q(('revoked_reason__isnull', True), models.Q(('revoked_reason', ''), _negated=True), _connector='OR'), name='access_role_revocation_reason_present')],
            },
        ),
    ]
