# Generated by Django 5.2.17 on 2026-09-15 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('account_id', models.UUIDField(primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=False)),
                ('changed_by_id', models.UUIDField()),
                ('changed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True, null=True)),
                ('seller_id', models.UUIDField(db_index=True, null=True)),
                ('kind', models.CharField(choices=[('physical', 'Физический'), ('digital', 'Цифровой черновик'), ('common', 'Общая карточка')], max_length=16)),
                ('unit', models.CharField(choices=[('pc', 'шт.'), ('kg', 'кг'), ('m', 'м')], max_length=2)),
                ('unit_locked', models.BooleanField(default=False)),
                ('draft', models.JSONField(default=dict)),
                ('draft_version', models.PositiveIntegerField(default=0)),
                ('published', models.JSONField(null=True)),
                ('published_version', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ('physical', 'digital', 'common'))), name='catalog_product_kind_valid'), models.CheckConstraint(condition=models.Q(('unit__in', ('pc', 'kg', 'm'))), name='catalog_product_unit_valid'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'common'), ('owner_id__isnull', True), ('seller_id__isnull', True)), models.Q(models.Q(('kind', 'common'), _negated=True), ('owner_id__isnull', False), ('seller_id__isnull', False)), _connector='OR'), name='catalog_product_ownership_valid'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'digital'), _negated=True), ('published__isnull', True), _connector='OR'), name='catalog_no_digital_publication')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attested_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_default', 'name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('seller_id', 'name'), name='catalog_location_name_unique'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('seller_id',), name='catalog_one_default_location')],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(null=True)),
                ('published_version', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('withdrawn', 'Снят')], default='draft', max_length=16)),
                ('withdrawal_version', models.PositiveIntegerField(default=0)),
                ('restore_version', models.PositiveIntegerField(null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('price_version', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.storagelocation')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.variant')),
            ],
            options={
                'ordering': ('location__name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(allow_unicode=True, max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('required', models.BooleanField(default=False)),
                ('values', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalog.category')),
            ],
            options={
                'ordering': ('label', 'id'),
                'constraints': [models.UniqueConstraint(fields=('category', 'key'), name='catalog_attribute_key_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='catalog_variant_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'published', 'withdrawn'))), name='catalog_variant_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('variant', 'location'), name='catalog_one_stock_per_location'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='catalog_stock_nonnegative'),
        ),
    ]
