# Generated by Django 5.2.17 on 2026-09-15 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('category', 'Категория'), ('attribute', 'Характеристика'), ('common', 'Общая карточка')], max_length=16)),
                ('target_id', models.UUIDField(null=True)),
                ('text', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewer_id', models.UUIDField(null=True)),
                ('response', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_id', models.UUIDField()),
                ('source_version', models.PositiveIntegerField()),
                ('target_version', models.PositiveIntegerField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=2000)),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('stale', 'Данные изменились')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewer_id', models.UUIDField(null=True)),
                ('review_reason', models.CharField(blank=True, max_length=1024)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_requests', to='catalog.variant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_requests', to='catalog.variant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OfferLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.matchrequest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_links', to='catalog.variant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_offers', to='catalog.variant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('source', 'target'), name='catalog_one_pending_match'),
        ),
        migrations.AddConstraint(
            model_name='offerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('source',), name='catalog_one_active_offer_link'),
        ),
    ]
