# Generated by Django 5.2.17 on 2026-09-16 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_common_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_id', 'product'), name='catalog_saved_product_unique')],
            },
        ),
    ]
