# Generated by Django 5.2.17 on 2026-09-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_public_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('buyer_id', models.UUIDField(db_index=True)),
                ('request', models.JSONField()),
                ('lines', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('held', 'В резерве'), ('committed', 'Продано'), ('released', 'Резерв снят')], default='held', max_length=12)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0), models.Q(models.Q(('quantity__isnull', True), ('reserved_quantity', 0)), models.Q(('quantity__isnull', False), ('reserved_quantity__lte', models.F('quantity'))), _connector='OR')), name='catalog_stock_reserve_valid'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='catalog.stock'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('held', 'committed', 'released'))), name='catalog_reservation_state_valid'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='catalog.inventoryreservation'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.UniqueConstraint(fields=('reservation', 'stock'), name='catalog_reservation_stock_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventoryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='catalog_allocation_positive'),
        ),
    ]
