from open_marketplace.identity.application import (
    add_totp_requirement,
    authenticate_account,
    begin_mandatory_totp_recovery,
    begin_totp_setup,
    block_account,
    change_password,
    check_email_throttle,
    check_throttle,
    complete_mandatory_totp_recovery,
    disable_optional_totp,
    enable_totp,
    get_session_security_snapshot,
    list_sessions,
    log_out_session,
    query_accounts,
    reauthenticate_session,
    recover_mandatory_totp,
    register_account,
    remove_totp_requirement,
    enable_invited_service_totp,
    provision_service_account_for_invitation,
    restart_expired_invited_service_totp,
    replace_recovery_codes,
    request_password_reset,
    require_live_session_security_snapshot,
    reset_password,
    revoke_other_sessions,
    revoke_session,
    revoke_sessions_for_security_event,
    unblock_account,
    verify_email,
)
from open_marketplace.identity.domain import (
    AccountId,
    AccountQuery,
    AccountSnapshot,
    AuthenticationResult,
    NeutralAccepted,
    SessionRevocationReason,
    SessionSecuritySnapshot,
    SessionView,
    ThrottleDecision,
    ThrottleScope,
    TotpSetupView,
)
from open_marketplace.identity.models import Account, TotpCredential


def get_account_snapshot(account_id: AccountId) -> AccountSnapshot:
    account = Account.objects.get(pk=account_id)
    return AccountSnapshot(
        id=account.id,
        email=account.email,
        kind=account.kind,
        state=account.state,
        email_verified_at=account.email_verified_at,
        totp_enabled=TotpCredential.objects.filter(
            account=account,
            disabled_at__isnull=True,
        ).exists(),
    )


__all__ = (
    "AccountQuery",
    "AccountSnapshot",
    "AuthenticationResult",
    "NeutralAccepted",
    "SessionRevocationReason",
    "SessionSecuritySnapshot",
    "SessionView",
    "ThrottleDecision",
    "ThrottleScope",
    "TotpSetupView",
    "add_totp_requirement",
    "authenticate_account",
    "begin_mandatory_totp_recovery",
    "begin_totp_setup",
    "block_account",
    "change_password",
    "check_email_throttle",
    "check_throttle",
    "complete_mandatory_totp_recovery",
    "disable_optional_totp",
    "enable_totp",
    "enable_invited_service_totp",
    "get_account_snapshot",
    "get_session_security_snapshot",
    "list_sessions",
    "log_out_session",
    "query_accounts",
    "reauthenticate_session",
    "recover_mandatory_totp",
    "register_account",
    "provision_service_account_for_invitation",
    "restart_expired_invited_service_totp",
    "remove_totp_requirement",
    "replace_recovery_codes",
    "request_password_reset",
    "require_live_session_security_snapshot",
    "reset_password",
    "revoke_other_sessions",
    "revoke_session",
    "revoke_sessions_for_security_event",
    "unblock_account",
    "verify_email",
)
