# Generated by Django 5.2.17 on 2026-09-03 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(unique=True)),
                ('approved_version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('awaiting_owner_totp', 'Awaiting owner TOTP'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], max_length=32)),
                ('restriction_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_profiles', to='seller_onboarding.sellerapplication')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('application', 'approved_version'), name='seller_profile_application_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='SellerReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('request_changes', 'Request changes'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=32)),
                ('reason', models.TextField()),
                ('reviewer_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('request_id', models.UUIDField(db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='seller_onboarding.sellerapplication')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('application', 'version_number'), name='seller_review_decision_version_unique')],
            },
        ),
    ]
