# Generated by Django 5.2.17 on 2026-09-16 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_saved_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=40)),
                ('initialized_at', models.DateTimeField()),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_inventory', to='catalog.variant')),
            ],
            options={
                'db_table': 'demo_orders_inventory',
            },
        ),
        migrations.CreateModel(
            name='DemoOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_id', models.UUIDField()),
                ('buyer_id', models.UUIDField(db_index=True)),
                ('seller_account_id', models.UUIDField(db_index=True)),
                ('seller_profile_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('variant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=512)),
                ('variant_label', models.CharField(max_length=512)),
                ('seller_display_name', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, max_digits=40)),
                ('state', models.CharField(choices=[('pending', 'Ожидает симуляции'), ('paid', 'Оплачено в симуляции'), ('handed_over', 'Передано в симуляции'), ('completed', 'Завершено в симуляции'), ('cancelled', 'Отменено в симуляции')], default='pending', max_length=16)),
                ('simulated_payment_status', models.CharField(choices=[('pending', 'Ожидает симуляции'), ('success', 'Успешно в симуляции'), ('declined', 'Отклонено в симуляции'), ('refunded', 'Возвращено в симуляции')], default='pending', max_length=16)),
                ('inventory_returned_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'demo_orders_order',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('buyer_id', 'intent_id'), name='demo_orders_buyer_intent_unique')],
            },
        ),
        migrations.CreateModel(
            name='DemoOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='demo_orders.demoorder')),
            ],
            options={
                'db_table': 'demo_orders_order_event',
                'ordering': ('occurred_at', 'id'),
            },
        ),
    ]
