# Generated by Django 5.2.17 on 2026-09-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("buyer_id", models.UUIDField(db_index=True, unique=True)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("intent_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={"db_table": "demo_orders_cart"},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant_id", models.UUIDField(db_index=True)),
                ("product_id", models.UUIDField()),
                ("title", models.CharField(max_length=512)),
                ("variant_label", models.CharField(max_length=512)),
                ("seller_name", models.CharField(max_length=256)),
                ("seller_id", models.UUIDField()),
                ("unit", models.CharField(max_length=2)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=19)),
                ("confirmed_unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("cart", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="items", to="demo_orders.cart")),
            ],
            options={"db_table": "demo_orders_cart_item", "ordering": ("seller_name", "variant_id", "id")},
        ),
        migrations.CreateModel(
            name="CartCheckoutReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("intent_id", models.UUIDField()),
                ("revision", models.PositiveBigIntegerField()),
                ("order_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField()),
                ("cart", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="checkout_receipts", to="demo_orders.cart")),
            ],
            options={"db_table": "demo_orders_cart_checkout_receipt"},
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(fields=("cart", "variant_id"), name="demo_orders_cart_variant_unique"),
        ),
        migrations.AddConstraint(
            model_name="cartcheckoutreceipt",
            constraint=models.UniqueConstraint(fields=("cart", "intent_id"), name="demo_orders_cart_intent_unique"),
        ),
    ]
