# Generated by Django 5.2.17 on 2026-09-02 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=64)),
                ('format_version', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('encrypted_delivery', models.BinaryField(null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('leased_by', models.CharField(max_length=128, null=True)),
                ('lease_expires_at', models.DateTimeField(db_index=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=20)),
                ('last_safe_error', models.CharField(max_length=128, null=True)),
                ('succeeded_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['state', 'next_attempt_at', 'created_at', 'id'], name='outbox_ready_idx'), models.Index(fields=['state', 'lease_expires_at', 'created_at', 'id'], name='outbox_lease_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('format_version', 1)), name='outbox_format_version_1')],
            },
        ),
    ]
