# Generated by Django 5.2.17 on 2026-09-02 13:40

import open_marketplace.audit.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_id', models.UUIDField(db_index=True, null=True)),
                ('effective_role', models.CharField(max_length=64, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=128)),
                ('result', models.CharField(db_index=True, max_length=64)),
                ('reason', models.TextField(null=True)),
                ('request_id', models.UUIDField(db_index=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('html', 'HTML'), ('admin', 'Admin'), ('command', 'Command'), ('worker', 'Worker')], max_length=16)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['object_type', 'object_id', '-occurred_at', '-id'], name='audit_object_history_idx')],
            },
            managers=[
                ('objects', open_marketplace.audit.models.AuditEntryManager()),
            ],
        ),
    ]
