# Generated by Django 5.2.17 on 2026-09-16 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_id', models.UUIDField(editable=False, unique=True)),
                ('reservation_id', models.UUIDField(editable=False, unique=True)),
                ('buyer_id', models.UUIDField(db_index=True, editable=False)),
                ('lines', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=40)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('state', models.CharField(choices=[('awaiting_payment', 'Ожидает подтверждения оплаты'), ('paid', 'Оплачено'), ('cancelled', 'Отменено')], db_index=True, default='awaiting_payment', max_length=24)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='commerce_order_total_nonnegative'), models.CheckConstraint(condition=models.Q(('currency', 'RUB')), name='commerce_order_currency_rub'), models.CheckConstraint(condition=models.Q(('state__in', ('awaiting_payment', 'paid', 'cancelled'))), name='commerce_order_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='CommerceOrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=24)),
                ('action', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField(null=True)),
                ('occurred_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='commerce.commerceorder')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='tbank_safe_deal', max_length=32)),
                ('provider_order_id', models.CharField(max_length=64, unique=True)),
                ('deal_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount_kopecks', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('state', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('authorized', 'Авторизовано'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('reversed', 'Отменено провайдером'), ('refunded', 'Возвращено провайдером')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent', to='commerce.commerceorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('provider_status', models.CharField(max_length=32)),
                ('amount_kopecks', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='commerce.paymentintent')),
            ],
            options={
                'ordering': ('received_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('provider', 'tbank_safe_deal')), name='payment_intent_provider_tbank'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'RUB')), name='payment_intent_currency_rub'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kopecks__gt', 0)), name='payment_intent_amount_positive'),
        ),
    ]
