# Generated by Django 5.2.17 on 2026-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='state',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('authorized', 'Авторизовано'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('reversed', 'Отменено провайдером'), ('refunded', 'Возвращено провайдером'), ('partial_refund', 'Частично возвращено провайдером')], db_index=True, default='pending', max_length=16),
        ),
    ]
