# Generated by Django 5.2.17 on 2026-09-16 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_paymentintent_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_account_id', models.UUIDField(db_index=True)),
                ('seller_profile_id', models.UUIDField(db_index=True)),
                ('delivery_mode', models.CharField(choices=[('cdek', 'СДЭК'), ('seller', 'Доставка продавцом')], max_length=6)),
                ('client_reference', models.CharField(max_length=30, unique=True)),
                ('lines', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Ожидает планирования'), ('ready', 'Готово к передаче'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='commerce.commerceorder')),
            ],
            options={
                'ordering': ('seller_account_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField(null=True)),
                ('occurred_at', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='commerce.fulfillmentshipment')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='fulfillmentshipment',
            constraint=models.UniqueConstraint(fields=('order', 'seller_account_id'), name='commerce_one_shipment_per_seller'),
        ),
    ]
