# Generated by Django 5.2.17 on 2026-09-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_event_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillmentevent',
            options={'ordering': ('shipment_id', 'sequence')},
        ),
    ]
