# Generated by Django 5.2.17 on 2026-09-16 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_fulfillmentevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_id', models.UUIDField(db_index=True, unique=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('intent_id', models.UUIDField(unique=True)),
                ('items', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommerceCartCheckoutReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_id', models.UUIDField()),
                ('revision', models.PositiveBigIntegerField()),
                ('order_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_receipts', to='commerce.commercecart')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart', 'intent_id'), name='commerce_cart_intent_unique')],
            },
        ),
    ]
