# Generated by Django 5.2.17 on 2026-09-18 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_commercecart_commercecartcheckoutreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceDeliveryAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("buyer_id", models.UUIDField(db_index=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("recipient_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=16)),
                ("country_code", models.CharField(default="RU", max_length=2)),
                ("postal_code", models.CharField(max_length=6)),
                ("region", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("street", models.CharField(max_length=160)),
                ("building", models.CharField(max_length=40)),
                ("apartment", models.CharField(blank=True, max_length=40)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(country_code="RU"),
                        name="commerce_delivery_address_country_ru",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="commerceorder",
            name="delivery_address",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="commercecartcheckoutreceipt",
            name="delivery_address_id",
            field=models.UUIDField(null=True),
        ),
    ]
