# Generated by Django 5.2.17 on 2026-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0007_commercedeliveryaddress_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillmentshipment",
            name="packages",
            field=models.JSONField(default=list),
        ),
    ]
