# Generated by Django 5.2.17 on 2026-09-02 12:30

import open_marketplace.identity.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kind', models.CharField(choices=[('ordinary', 'Ordinary'), ('service', 'Service')], default='ordinary', max_length=16)),
                ('state', models.CharField(choices=[('pending_email_verification', 'Pending email verification'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending_email_verification', max_length=32)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'db_table': 'identity_account',
            },
            managers=[
                ('objects', open_marketplace.identity.managers.AccountManager()),
            ],
        ),
    ]
