# Generated by Django 5.2.17 on 2026-09-02 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('mandatory_totp_recovery', 'Mandatory TOTP recovery')], max_length=32)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revoked_reason', models.CharField(max_length=64, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_time_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_one_time_token',
                'indexes': [models.Index(fields=['account', 'purpose', 'created_at', 'id'], name='identity_token_subject_idx'), models.Index(fields=['purpose', 'expires_at'], name='identity_token_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='identity_token_expiry_after_create'), models.CheckConstraint(condition=models.Q(('used_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='identity_token_not_used_and_revoked'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_reason__isnull', True)), models.Q(('revoked_at__isnull', False), ('revoked_reason__isnull', False)), _connector='OR'), name='identity_token_revocation_pair')],
            },
        ),
    ]
