# Generated by Django 5.2.17 on 2026-09-02 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_recoverycode_totpcredential_totprequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_audit_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='block_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='blocked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='blocked_by_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='totpsetup',
            name='recovery_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='totp_setups', to='identity.onetimetoken'),
        ),
        migrations.AlterField(
            model_name='totpsetup',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='totp_setups', to='identity.accountsession'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('block_audit_id__isnull', False), ('block_reason__isnull', False), ('blocked_at__isnull', False), ('blocked_by_id__isnull', False), ('state', 'blocked')), models.Q(models.Q(('state', 'blocked'), _negated=True), ('block_audit_id__isnull', True), ('block_reason__isnull', True), ('blocked_at__isnull', True), ('blocked_by_id__isnull', True)), _connector='OR'), name='identity_account_block_metadata_state'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('block_reason__isnull', True), models.Q(('block_reason', ''), _negated=True), _connector='OR'), name='identity_account_block_reason_present'),
        ),
        migrations.AddConstraint(
            model_name='totpsetup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recovery_token__isnull', True), ('session__isnull', False)), models.Q(('recovery_token__isnull', False), ('session__isnull', True)), _connector='OR'), name='identity_totp_setup_exactly_one_binding'),
        ),
    ]
