# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0005_account_administration_and_totp_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("registration_email", "Registration email"),
                            ("password_reset_email", "Password reset email"),
                            ("staff_invitation_email", "Staff invitation email"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "key_kind",
                    models.CharField(
                        choices=[("account", "Account"), ("source", "Source")],
                        max_length=8,
                    ),
                ),
                ("key_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("allowed_attempt_count", models.PositiveIntegerField(default=0)),
                ("blocked_until", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "identity_security_throttle",
                "indexes": [
                    models.Index(
                        fields=["scope", "window_started_at"],
                        name="identity_throttle_expiry_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key_kind", "key_hash"),
                        name="identity_unique_throttle_scope_kind_hash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(key_hash__regex=r"^[0-9a-f]{64}$"),
                        name="identity_throttle_key_hash_format",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(blocked_until__isnull=True)
                            | models.Q(
                                blocked_until__gt=models.F("window_started_at")
                            )
                        ),
                        name="identity_throttle_block_after_window_start",
                    ),
                ],
            },
        ),
    ]
